"""update

Revision ID: 1bd2ca4aebc9
Revises: 574c537d3604
Create Date: 2025-11-25 16:30:11.859817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd2ca4aebc9'
down_revision = '574c537d3604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('content_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('icon')
        batch_op.drop_column('slug')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('content_text')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('media_url')
        batch_op.drop_column('type')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
